on:
  schedule:
    - cron: '0 16 * * 1-5'

name: slack-cron

jobs:
  slack-cron:
    name: "Posting to the work slack"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: LTLA/actions-anime-gif-slackbot@master
        with:
          webhook: ${{ secrets.SLACK_WORK_WEBHOOK }}
